version: '3'
services:
  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - DBHOST=${DBHOST}
      - TOKEN=${TOKEN}
      - DBNAME=${DBNAME}
  
  database:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=${DBNAME}
